# Numpy

## 1. Import Numpy Library

In [ ]:
import numpy as np


## 2. Initialize the array, which is matrix.

In [3]:
a = np.array([1, 2, 3])    # rank가 1인 배열 생성
print(a.shape)             # 출력 (3, ) 
print(a[0], a[1], a[2])    # 출력 1, 2,
a[0] = 5                   # 요소를 변경 - "[5, 2, 3]"

b = np.array([[1, 2, 3], [4, 5, 6]])   # rank가 2인 배열 생성

print(b.shape)                      # 출력 (2, 3) --> 3x2 행렬
print(b[0, 0], b[0, 1], b[1, 0])    # 출력 "1, 2, 4"


(3,)
1 2 3
(2, 3)
1 2 4


In [43]:
a = np.zeros((2, 2))    # 모든 값이 0인 배열 생성
b = np.ones((1, 2))     # 모든 값이 1인 배열 생성

c = np.full((2, 2), 7)  # 모든 값이 특정 상수인 배열 생성
d = np.eye(2)           # 2x2 단위 행렬 생성

e = np.random.random((2, 2))    # 임의의 값으로 채워진 배열 생성


[[1. 0.]
 [0. 1.]]


## 3. Array indexing,                                                          similar to the python list indexing

In [5]:
# shape (3, 4), 4x3 행렬

a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# 슬라이싱을 이용하여 첫 두 행과 1열, 2열로 이루어진 부분배열 생성

# b는 shape가 (2, 2)인 배열이 됩니다: [[2, 3], [6, 7]]
b = a[:2, 1:3]


In [6]:
# 슬라이싱된 배열은 원본 배열과 같은 데이터를 참조합니다
# 즉 슬라이싱된 배열을 수정하면 원본 배열 역시 수정됩니다.

print(a[0, 1])    # 출력 2
b[0, 0] = 77      # b[0, 0]은 a[0, 1]과 같은 데이터 입니다
print(a[0, 1])    # 출력 77


2
77


In [9]:
# 행으로 조회

# 1. 정수 인덱스와 슬라이스를 섞으면 더 낮은 순위의 배열 생성

row_r1 = a[1, :]               # Rank 1
print(row_r1, row_r1.shape)    # [5, 6, 7, 8] (4, )


[5 6 7 8] (4,)


In [10]:
# 행으로 조회

# 2. 슬라이스만 사용하면 원래 배열과 동일한 순위의 배열 생성
  
row_r2 = a[1:2, :]             # Rank 2
print(row_r2, row_r2.shape)    #[[5, 6, 7, 8]] (1, 4)

[[5 6 7 8]] (1, 4)


In [11]:
# 열로 조회 

col_1 = a[:, 1]
print(col_1, col_1.shape)    # [2, 6, 10] (3, )

col_2 = a[:, 1:2]
print(col_2, col_2.shape)    # [[2], [6], [10]] (3, 1)


[77  6 10] (3,)
[[77]
 [ 6]
 [10]] (3, 1)


In [12]:
a = np.array([[1, 2], [3, 4], [5, 6]])
b = a[[0, 1, 2]]

# "[1 4 5]"
print(a[[0, 1, 2], [0, 1, 0]])
print(np.array([a[0, 0], a[1, 1], a[2, 0]])) 


[1 4 5]
[1 4 5]


In [17]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

# element 선택 방식
b = np.arange(4)
c = np.array([0, 2, 0, 1])
print(a[b, c])    # [1, 6, 7, 11]


[ 1  6  7 11]


In [18]:
# 선택된 모든 element를 변경
a[b, c] += 10

# [[11, 2, 3], [4, 5, 16], [17, 8, 9], [10, 21, 12]]


In [19]:
a = np.array([[1, 2], [3, 4], [5, 6]])
bool_idx = (a > 2)
print(bool_idx)
# [[False, False], [True, True], [True, True]]

print(a[bool_idx])    # [3, 4, 5, 6]
print(a[a > 2])       # [3, 4, 5, 6]


[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


## 4. Datatypes.

In [20]:
x = np.array([1, 2])    
print(x.dtype)          # int64

x = np.array([1.0, 2.0])
print(x.dtype)          # float64

x = np.array([1, 2], dtype = np.int32)
print(x.dtype)          # int32


int32
float64
int32


In [22]:
# Numpy Array
x = np.array([1, 2])    
print(type(x))          # <class 'numpy.ndarray'>

# numpy.ndarray to list
y = x.tolist()
print(y)                # [1, 2]
print(type(y))          # <class 'list'>


<class 'numpy.ndarray'>
[1, 2]
<class 'list'>


## 5. Array Math.

In [23]:
x = np.array([[1, 2], [3, 4]], dtype = np.float64)
y = np.array([[5, 6], [7, 8]], dtype = np.float64)

print(x + y)                # 더하기
print(np.add(x, y))         # 더하기

print(x - y)                # 빼기
print(np.subtract(x, y))    # 빼기


[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [26]:
print(x * y)                # 곱하기
print(np.multiply(x, y))    # 곱하기

print(x / y)                # 나누기
print(np.divide(x, y))      # 나누기

print(np.sqrt(x))           # 제곱


[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [27]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

v = np.array([9, 10])
w = np.array([11, 12])


In [28]:
# (1, 2) * (1, 2), 219
print(v.dot(w))
print(np.dot(v, w))

# (2, 2) * (1, 2), [26 67]
print(x.dot(v))
print(np.dot(x, v))


219
219
[29 67]
[29 67]


In [29]:
# (2, 2) * (2, 2), rank 2 array
# [[19 22], [43 50]]
print(x.dot(y))
print(np.dot(x, y))


[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [30]:
x = np.array([[1, 2], [3, 4]])

print(np.sum(x)) # 전체 합산, 10

print(np.sum(x, axis=0)) # 열 합산, [4 6]

print(np.sum(x, axis=1)) # 행 합산, [3 7]


10
[4 6]
[3 7]


In [31]:
x = np.array([[1, 2], [3, 4]])
print(x)   # [[1 2], [3 4]]

# 전치 행렬
print(x.T) # [[1 3], [2 4]]


[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [32]:
x = np.array([1, 2, 3, 4], ndmin=2) # ndmin 없이 해보기
print(x)       # [[1 2 3 4]]
print(x.shape) # (1, 4)

# 전치 행렬
print(x.T)    # [[1], [2], [3], [4]]

[[1 2 3 4]]
(1, 4)
[[1]
 [2]
 [3]
 [4]]


## 6. Broadcasting

In [36]:
# 서로 다른 모양의 배열 생성
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
v = np.array([1, 0, 1])


In [35]:
print(x)
# [[ 1 2 3], [ 4 5 6]]

print(x * 2)
# [[ 2 4 6], [ 8 10 12]]


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]
 [20 22 24]]


In [34]:
# broadcasting, v를 x의 각 행에 더한다.
y = x + v 
print(y) # "[[ 2 2 4], [ 5 5 7], [ 8 8 10], [11 11 13]]


[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [37]:
v = np.array([1, 2, 3])                 # shape (3,)
x = np.array([[1, 2, 3], [4, 5, 6]])    # shape (3, 2), 3x2 행렬
print(x + v)
# [[2 4 6], [5 7 9]]


[[2 4 6]
 [5 7 9]]


In [38]:
v = np.array([1, 2, 3])    # shape (3,)
w = np.array([4, 5])       # shape (2,)

# 1x3 행렬 * 2x1 행렬 => 2x3 행렬
print(np.reshape(v, (3, 1)))
print(np.reshape(v, (3, 1)) * w)


[[1]
 [2]
 [3]]
[[ 4  5]
 [ 8 10]
 [12 15]]


In [39]:
# 3x2 의 전치 행렬(2x3)과 Array w (2,) 덧셈 => 2x3 행렬
print(x.T + w)

# 결과 2x3 행렬의 전치 행렬 => 3x2 행렬
print((x.T + w).T)
# [[ 5 6 7], [ 9 10 11]]


[[ 5  9]
 [ 6 10]
 [ 7 11]]
[[ 5  6  7]
 [ 9 10 11]]


In [45]:
# w를 1x2 행렬로 변경
print(np.reshape(w, (2, 1)))

# 3x2 행렬과 1x2 행렬 덧셈
print(x + np.reshape(w, (2, 1)))


[[4]
 [5]]
[[ 5  6  7]
 [ 9 10 11]]
